language: java
jdk:
- oraclejdk7

branches:
  except:
    - blackbox-images

install:
  - git clone --depth=50 --branch=master https://github.com/nom-tam-fits/blackbox-images.git ../blackbox-images
  - mvn install -DskipTests=true

script:
    - mvn test ; export MAVEN_RESULT=$?
    - if [ "$MAVEN_RESULT" -ne 0 ]; then exit 1; fi
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn clean deploy --quiet --settings settings.xml; fi

after_success:
  - mvn clean test jacoco:report coveralls:report
 
notifications:
  email:
    - richard.vannieuwenhoven@adesso.at
    - Tom.McGlynn@nasa.gov
    - erik.koerber@gmail.com
    
env:
  - MAVEN_OPTS="-Xmx=2G"
 global:
  - TERM=dumb
  - secure: "bKh2my2DsryV1AgANX4DvhgttoTIeGs/QlEdRg5zAGQ8+4s7v4qw90iONMa/HSWuZCha8zzZdiplyXevY/CqICVOp8YtJ6SwfUSZpwNnKBVjwWKWI4uIRpDONYiMuVwSMgusREphiJY2A1raohXl48cP2JexEY+ftCSY11P2rLg="
  - secure: "HoAeUJC7l85KrP47PN9jcDvyLpssmX/n9dj7l0WkjQKu+yH6rnHw7P8KxAwWgntjj1fdefotSbUd82FNziQPyNKOr/PTm71eyWjkoeMpRWabmP6Jw6aosmrtrfkHj2jWb83gXK3p8LX/TLNgcHjP4vv0Gr/GJOEVT1PPOtQiZuo="
  
